# Generated by Django 5.2.16 on 2026-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
