# Generated by Django 5.2.16 on 2026-07-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('userphone', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
