# Generated by Django 5.2.16 on 2026-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='useremail',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userpassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userphone',
            field=models.CharField(max_length=15),
        ),
    ]
