# Generated by Django 5.2.16 on 2026-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdetails_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userphone',
            field=models.CharField(max_length=10),
        ),
    ]
