# Generated by Django 5.2.16 on 2026-08-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
