# Generated by Django 5.2.16 on 2026-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='productid',
            field=models.IntegerField(default=0),
        ),
    ]
