# Generated by Django 5.2.16 on 2026-09-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
